### ISSUE TITLE
Give a visual clue in the report as for the document being tested?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-tests#75]
Although we concentrated on RS tests, we will have to report on three rec-track documents. Putting aside the issue on whether the current test harness can cover all requirements in the various document, the current report gives very little clue on the "origin" (apart from links to the relevant statement). We could:

* add three columns for each test in the test description tables referring to the documents being tested. The information is present in the current metadata (via the `dcterms:isReferencedBy` statements). (Many test will have references to several documents.)
* add a new metadata item (a bit similar to #74) designating the "primary" document being tested by the test, and display that value in the tables

Do we need something like that? If yes, do we need the concept of "primary" document?

Cc @dauwhe @dlazin @wareid @mattgarrish

**Comment by dlazin** [comment]
Hmm, I was thinking we didn't have to worry about this, but could be because I misunderstand the process. I was imagining:

1) We present pages like https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-pub-identifiers to the reviewers, demonstrating that ~every statement has a test.

2) https://w3c.github.io/epub-tests/ demonstrates that all the tests pass in at least 2 RSes (and, where they do not, we modify the spec to remove MUSTs or whatever).

I was not thinking that you need to go *from* the tests back to the specs. Is this a legitimate problem?

**Comment by iherman** [comment]
The fundamental issue is that reviewers should (easily) see that we aren't only testing the RS specification, but the core and a11y, too. This information is not readily available in the test report only.

But, maybe, it is indeed enough if we point them to the editors' drafts that shows the existence of the tests if they are in doubt, and I am being too cautious :-)

**Comment by iherman** [comment]
Thinking about this further, this may indeed be unnecessary at this point. Withdrawing, i.e., closing the issue without further actions.
